name: Suggestion
description: Make any suggestion to us
title: "[Suggestion]: "
labels: [enhancement]
assignees:
  - octocat
body:
  - type: checkboxes
    id: checkbox1
    attributes:
      label: Have you checked if there's any similar suggestions ?
      description: "Please check this if your suggestion has already been requested by some other user."
      options:
        - label: I checked, there are no similar suggestions that have been reported.
          required: true
  - type: checkboxes
    id: checkbox3
    attributes:
      label: Are you using the latest Epic Fight ?
      description: "Please check if you are using our latest versions as we may or may not have added what you've suggested to us."
      options:
        - label: "I checked I'm using latest Epic Fight version."
          required: true
  - type: checkboxes
    id: checkbox4
    attributes:
      label: "Is this suggestion related to another mod? (i.e: add animations for X mod)"
      description: "Please note that most suggestions regarding other mods will most likely get denied as its not always up to us to fix it."
      options:
        - label: "This is related to other mods."
          required: false
  - type: input
    id: specify-mod
    attributes:
      label: The mod
      description: "Please specify the mod you want us to take a look at."
      placeholder: Mod name or URL.
    validations:
      required: false
  - type: dropdown
    id: mc-version
    attributes:
      label: Minecraft Version
      description: "Minecraft Version"
      options:
        - 1.16.5
        - 1.18.2
        - 1.19.2
        - 1.20.1
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What's your suggestion?
      description: "Please tell us as detailed as you can, your suggestions, ideas or overall anything that could be improved in epic fight."
    validations:
      required: true
